import Features from "../components/FeaturesComp/Features";
import Hero from "../components/Hero/Hero";
import Navbar from "../components/Navbar/Navbar";
import Stats from "../components/Stats/Stats";
export const metadata = {
  title: "feedly",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <header>
        <Navbar />
      </header>
      <main className="flex flex-col gap-6">
        <Hero />
        <Stats />
        <Features />
      </main>
    </>
  );
}
