import Navbar from "../components/Navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <div>
        <Navbar />
      </div>
    </>
  );
}
